pipeline {

    agent any

    parameters {
        string(
            name: 'REPO_URL',
            defaultValue: 'https://github.com/Dhruv-sha/nodejs-application-deploy-github-actions.git',
            description: 'GitHub repository URL to deploy',
            trim: true
        )
    }

    stages {

        stage('Checkout Platform') {
            steps {
                checkout scm
            }
        }

        stage('Detect Application') {
            steps {
                sh '''
                    chmod +x platform/scripts/detect-app.sh
                    cd application && ../platform/scripts/detect-app.sh
                '''
            }
        }

        stage('Verify') {
            steps {
                sh '''
                    echo ""
                    echo "Platform:"
                    ls -la

                    echo ""
                    echo "Application:"
                    ls -la application
                '''
            }
        }
    }
}